# Generated by Django 4.0.4 on 2024-01-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_type', models.CharField(choices=[('consumable', 'Consumable'), ('service', 'Service'), ('event', 'Event')], max_length=20)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
