# Generated by Django 4.0.4 on 2024-01-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='customer_tax',
        ),
    ]
