# Generated by Django 4.0.4 on 2024-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_orderproduct_description_alter_orderproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='description',
            field=models.TextField(),
        ),
    ]
