# Generated by Django 4.0.4 on 2024-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_products_customer_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
