# Generated by Django 4.0.4 on 2024-01-29 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import decimal

class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_products_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='customer_tax',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=5),

            preserve_default=False,
        ),
    ]
