# Generated by Django 4.0.4 on 2024-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_products_customer_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customer_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
