# Generated by Django 4.0.4 on 2024-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_orderproduct_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='description',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
