# Generated by Django 4.0.4 on 2024-01-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_products_customer_tax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
