# Generated by Django 4.0.4 on 2024-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_orderproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
