# Generated by Django 4.0.4 on 2024-01-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_customer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
