# Generated by Django 4.0.4 on 2024-01-31 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_saleorder_saleorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleorderitem',
            name='sale_order',
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
        migrations.DeleteModel(
            name='SaleOrderItem',
        ),
    ]
