# Generated by Django 4.0.4 on 2024-01-31 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_saleorderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('quotation_template', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('recurring_plan', models.CharField(max_length=50)),
                ('pricelist', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.customer')),
                ('products', models.ManyToManyField(to='Product.products')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.products')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.saleorder')),
            ],
        ),
    ]
