# Generated by Django 4.0.4 on 2024-01-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_saleorder_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='custom_id',
        ),
    ]
