# Generated by Django 4.0.4 on 2024-01-31 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_remove_saleorder_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='custom_id',
            field=models.CharField(default=datetime.datetime(2024, 1, 31, 11, 31, 43, 666384, tzinfo=utc), editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
