# Generated by Django 4.0.4 on 2024-01-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_saleorder_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='custom_id',
            field=models.CharField(default='SO001', editable=False, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.products')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.saleorder')),
            ],
        ),
    ]
