# Generated by Django 4.0.4 on 2024-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_saleorder_custom_id_saleorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='custom_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
