# Generated by Django 4.0.4 on 2024-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_alter_saleorder_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customer_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
