# Generated by Django 4.0.4 on 2024-02-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_products_customer_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleorderitem',
            name='sale_order',
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
        migrations.DeleteModel(
            name='SaleOrderItem',
        ),
    ]
